language: lua

matrix:
  include:

  - os: linux
    compiler: gcc
  - os: osx
    compiler: clang
#    env:
#     - PLATFORM=''

script:

branches:
  only:
    - master

after_success:

notifications:
  email: false

